version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: uptime-postgres
    restart: always
    environment:
      POSTGRES_DB: uptime_monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # this is for data persistence
volumes:
  postgres_data:


